/*
 * HmTwitterGrokWeb v 2.0.2.1
 *
 * Copyright (c) 2025-2026 Akitsugu Komiyama
 * under the MIT License
 */


hidemaruversion "9.50.04";

setcompatiblemode 0x08000000;

jsmode @"WebView2\HmTwitterGrokWeb";

js {

// ------------- 会話エンジンの設定項目 -------------

const baseUrl = "https://x.com/i/grok";

const renderPaneCustomParam = {
    place: "rightside",            // leftside | rightside | upside | downside
    size: 900,                     // 左や右の配置の時は、横幅のこと。上や下の配置の時は縦幅のこと。
};

const isOneAtTimeAIRenderPane = 1; // AI関連のレンダリング枠は(他の種類のAIも含め)１つだけにする。(複数起動しそうになると、前のものが閉じる）

// --------------------------------------------------

const renderPaneTargetName = "HmTwitterGrokWeb";

const currentMacroDirectory = currentmacrodirectory();

const script = hidemaru.loadTextFile(currentMacroDirectory + "\\HmConvAIWeb.js");
eval(script);

function onPrevKeySendDecorator() {
    try {
        browserpanecommand({target:"_each", focusinputfield:'textarea[placeholder="どんなことでもお尋ねください"]'});
    } catch(e) {
    }
}

doMain();

} // js
